spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect


  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaf8uhmpl8Y6Bjz90h7
            client-secret: 0TnoYdVoK7ZMggd1Tu1rDGZQOV_TB35xJlY82CZU
        provider:
          okta:
            authorization-uri: https://dev-420480.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://dev-420480.oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://dev-420480.oktapreview.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-420480.oktapreview.com/oauth2/default/v1/keys

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

server:
  port: 9090
  servlet:
  contextPath: /spring
